"""initial schema

Revision ID: a6bbc482cfae
Revises: 
Create Date: 2026-03-18 23:10:50.462404

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6bbc482cfae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id')
    )
    op.create_table('zec_price_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zec_price_history_timestamp'), 'zec_price_history', ['timestamp'], unique=False)
    op.create_table('org_wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('spending_key', sa.String(length=500), nullable=False),
    sa.Column('viewing_key_full', sa.String(length=500), nullable=False),
    sa.Column('viewing_key_incoming', sa.String(length=500), nullable=False),
    sa.Column('pool', sa.Enum('orchard', 'sapling', name='walletpool'), nullable=False),
    sa.Column('balance_zec', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'contributor', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contributors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('monthly_rate_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wallet_address', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('active', 'pending', 'inactive', name='contributorstatus'), nullable=False),
    sa.Column('employment_type', sa.Enum('employee', 'contractor', name='employmenttype'), nullable=False),
    sa.Column('tax_jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('initiated_by', sa.UUID(), nullable=False),
    sa.Column('period_label', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'processing', 'completed', 'failed', name='payrollrunstatus'), nullable=False),
    sa.Column('total_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_zec', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('zec_rate_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('network_fee_zec', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('tx_id', sa.String(length=255), nullable=True),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('memo_template', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shared_viewing_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_wallet_id', sa.UUID(), nullable=False),
    sa.Column('shared_with', sa.String(length=255), nullable=False),
    sa.Column('key_type', sa.Enum('full', 'incoming', 'outgoing', name='viewingkeytype'), nullable=False),
    sa.Column('key_value', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_wallet_id'], ['org_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('gross_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_withheld_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('zec_amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('zec_rate_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('memo_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'confirmed', 'failed', name='payrollitemstatus'), nullable=False),
    sa.Column('tx_output_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('contributor_id', sa.UUID(), nullable=True),
    sa.Column('tx_id', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.Enum('incoming', 'outgoing', name='transactiondirection'), nullable=False),
    sa.Column('amount_zec', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('zec_rate_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('tx_type', sa.Enum('payroll', 'withdrawal', 'deposit', 'fee', name='transactiontype'), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('pool', sa.Enum('orchard', 'sapling', 'transparent', name='transactionpool'), nullable=False),
    sa.Column('memo_raw', sa.LargeBinary(), nullable=True),
    sa.Column('memo_decoded', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contributor_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('income', 'disposal', 'fee', name='taxeventtype'), nullable=False),
    sa.Column('amount_zec', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cost_basis_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('fair_value_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gain_loss_usd', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_basis_method', sa.Enum('fifo', 'lifo', 'hifo', 'acb', 'specific_id', name='costbasismethod'), nullable=False),
    sa.Column('holding_period', sa.Enum('short_term', 'long_term', name='holdingperiod'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contributor_id'], ['contributors.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tax_events')
    op.drop_table('transactions')
    op.drop_table('payroll_items')
    op.drop_table('shared_viewing_keys')
    op.drop_table('payroll_runs')
    op.drop_table('contributors')
    op.drop_table('users')
    op.drop_table('org_wallets')
    op.drop_index(op.f('ix_zec_price_history_timestamp'), table_name='zec_price_history')
    op.drop_table('zec_price_history')
    op.drop_table('organizations')
    # ### end Alembic commands ###
