"""add_payment_uri_to_payroll_runs

Revision ID: cfcee84fc3a8
Revises: c6e7fee21129
Create Date: 2026-03-19 16:31:51.051927

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcee84fc3a8'
down_revision: Union[str, None] = 'c6e7fee21129'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_wallets', 'zcash_wallet_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('payroll_runs', sa.Column('payment_uri', sa.String(length=8000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_runs', 'payment_uri')
    op.alter_column('org_wallets', 'zcash_wallet_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
